name: HACS repository validation

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Validate custom integration with HACS
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa
        with:
          category: integration
